### ISSUE TITLE
Call items in todo list

### ISSUE THREAD

**Issue by docterry** [pedcards/chipotle#1]

**Comment by pedcards** [comment]
Yes, I am for this.

-TC


On Feb 1, 2016, at 6:59 PM, docterry <notifications@github.com<mailto:notifications@github.com>> wrote:


—
Reply to this email directly or view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pedcards_chipotle_issues_1&d=CwMCaQ&c=aBkXpkKi7gN5fe5MqrMaN-VmRugaRb1IDRfSv2xVRy0&r=UGe3DskQjM43VWw32jK3rEjvjFBH8FEbnzcV6dl9wFQNsdHfmWKck35HrsiHi8pS&m=xXy8bBqczNBut9SMe8Kgbj8H9fufDzpEC6_Jbm5ddvc&s=Qj9t-L3ZzNtC01FLQOxJ4SQVZIYJSfjmbh3FnrKPPxw&e=>.

CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information protected by law. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by pedcards** [comment]
- <call> items automatically created during ICUmerge or Sur6merge (SURGCTR and CSR attg) as these will be surgical.
- <call> items created manually by anyone.
- <call> items recreated during initial currlist/archlist import.

Should be checked and removed via for tasklist.

**Comment by docterry** [comment]
Keep as <call> item rather than <todo> item for easier auditing of calls made.

**Comment by pedcards** [comment]
Either run fixcurrlist or auto fix issues. May be better to do both concurrently.

**Comment by pedcards** [comment]
fixcurrlist successfully reorganizes major nodes (including multiple <info> nodes), moves <plan/call> into <plan/tasks/call>.

**Comment by pedcards** [comment]
clicking CALL to check off item in taskLV should jump to callCards
