### ISSUE TITLE
Loading outside patient into Chipotle using the new instructions

### ISSUE THREAD

**Issue by abuell** [pedcards/chipotle#151]
Hi Terry,

I just got my first error when loading an outside patient into Chipotle using the new instructions. When I click the blank space after the patients name I get and error. The patient is Tofiga, Amotai'uziah vilvika skelton (Uziah), MRN is 1376121. Maybe his name it too long?

I'll send a screen shot of the error to you via Outlook.

thanks,
~Anya

**Comment by docterry** [comment]
Like the Lambada, the apostrophe is a forbidden character. By morphing it into a backtick "`", it looks consistent, but behaves normally.
