### ISSUE TITLE
entering a new patient  "."

### ISSUE THREAD

**Issue by abuell** [pedcards/chipotle#181]
Heyya,

When I add in a patient (not currently on a list) the name field only shows a .  

The patient's name does not carry over. It started out working so I think I may have broke it. OOPSIE

**Comment by docterry** [comment]
Aren't you supposed to be basking on a beach in Mexico?

**Comment by docterry** [comment]
So, yes. You must have been the one to break it. It had nothing to do with me changing the file handling last week while you were gone.
