### ISSUE TITLE
Chipotle not opening

### ISSUE THREAD

**Issue by abuell** [pedcards/chipotle#197]
I'm getting this error when opening chipotle:

the operation has timed out
error 0x80072EE2

**Comment by docterry** [comment]
This appears to have been a global network problem at SCH. Now resolved.

-TC


On Aug 24, 2018, at 8:41 AM, abuell <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm getting this error when opening chipotle:

the operation has timed out
error 0x80072EE2
