### ISSUE TITLE
Direct read Electronic Forecast and Stork List

### ISSUE THREAD

**Issue by pedcards** [pedcards/chipotle#38]
Use XLS reading sub (stored in GitHub Gist).
SaveCensus runs once a day.

**Comment by docterry** [comment]
`chmc16\Cardio\Fetal\`
`+--- "Copy of Upcoming NICU babies for CRD or ECMO.xlsx"`
`+--- "Upcoming NICU babies MAIN list.xlsx"`

**Comment by docterry** [comment]
`\\childrens\files\HCSchedules\Electronic Forecast\2016\
+--- 7-25 thru 7-31_2016 Electronic Forecast.xlsx
+--- August 2016-NW Cong.doc
`

**Comment by docterry** [comment]
Patti updates forecast file until she sends it on Fri.

**Comment by docterry** [comment]
Forecast XLS reader complete. Now to tune up the Stork reader.
