### ISSUE TITLE
Only update server when requested

### ISSUE THREAD

**Issue by pedcards** [pedcards/chipotle#4]
Should we even have a web interface? Does anyone even use it?
Security issues. 
Sync issues (although I believe that I have gotten around this with the double sync on each Chipotle startup).
Some clean-up happens during IO run, so would still need clean-up on Chipotle close.
- [ ] Rework io.ahk subs
- [ ] Add button

**Comment by pedcards** [comment]
Rework io.ahk subs

**Comment by pedcards** [comment]
Add button

**Comment by pedcards** [comment]
Apparently, Britton uses the interface whilst on-service. I have seen him using it (and I think that he got some negative feedback that he was checking his phone when he was probably actually doing something useful.

**Comment by pedcards** [comment]
It is time consuming to start a SCP session. Perhaps could do a quick cURL check to see if the file has changed first.

**Comment by pedcards** [comment]
Could probably remove Get It sub, since the existing currlist is the most current. 

Would strip down Save It. No need to perform get sub or compare parts. Only need to perform archive operations. Can archive be saved for Patti, e.g. when census is saved?

**Comment by pedcards** [comment]
Use `UrlDownloadToFile, URL, filename` to check file, parse last modified date. File will need to be in a readable folder. Need to be saved outside of patlist to avoid need for UW NetID.

**Comment by docterry** [comment]
Chipotle-web should include MRN of edits so io.ahk only has to scan the changed items.

**Comment by docterry** [comment]
Using `HTTP get` to trigger PHP. Successfully returns XML string.

**Comment by docterry** [comment]
Will get change XML from server if exists. Should step through each node, which will have node, mod date, editor. Compare and clone if does not exist in currlist. 

Move change XML to a temp name. Delete when success. 

How to keep concurrent server change from being missed?

**Comment by pedcards** [comment]
Switched back to simplexml.
