### ISSUE TITLE
Remove io process?

### ISSUE THREAD

**Issue by pedcards** [pedcards/chipotle#6]
Should we even have a web interface? Does anyone even use it?
Security issues. 
Sync issues (although I believe that I have gotten around this with the double sync on each Chipotle startup).
Some clean-up happens during IO run, so would still need clean-up on Chipotle close.

**Comment by docterry** [comment]
Could probably remove Get It sub, since the existing currlist is the most current. 

Would strip down Save It. No need to perform get sub or compare parts. Only need to perform archive operations. Can archive be saved for Patti, e.g. when census is saved?
