### ISSUE TITLE
Access for Natalya and Shannon

### ISSUE THREAD

**Issue by abuell** [pedcards/chipotle#75]
Hi,
Do Shannon and Natalya need to be given access to view CHIPOTLE? I tried to load it on Natalya's CIS but its giving me an access error.

They don't need to write in it. My thought for giving them access is that it will help them easily determine who the referring cardiologist is. There is an expectation that they include this information in their Outlook invites but they are not always informed by our staff and have to do a lot of manual digging to make it happen and it not always accurate.

Thanks,
Anya

**Comment by docterry** [comment]
Submitted IS Help req to add Shannon and Natalya to the CHIPOTLE list. Would it be worthwhile to have some scheduling tools for them? Perhaps have CHIPOTLE generate the Outlook appointment or something like that?

**Comment by abuell** [comment]
Perhaps. They haven't seen or used it yet so lets ease them in with this first and then see where it leads.
