### ISSUE TITLE
Update y.currlist when call date set

### ISSUE THREAD

**Issue by abuell** [pedcards/chipotle#82]
Hi Terry,

Two of Studer's patients are on the CICU call list but it didn't generate a date to call automatically when they were admitted for surgery. I'm trying to manually set the call task for tomorrow but its not letting me. I don't get an error of any sort, call center box just closes and then immediately reopens.

Thanks,
Anya

**Comment by pedcards** [comment]
The "Call sequence auto-initiate" is triggered when a patient meets all the following criteria: 
* on CSR list
* on either CICU or Cards lists
* has location "SURGCNTR"

The IcuMerge subroutine is only called when either the CSR or CICU list is updated.

If the patient goes to SURGCNTR but the CHIPOTLE list has not been updated, it will not trigger the auto-initiate. Both of these patients were inpatients so I suspect that the lists were not updated when their status changed to SURGCNTR.

**Comment by docterry** [comment]
It seems that both those patients have Call dates set for tomorrow. The problem may be that CHIPOTLE doesn't always update its internal information when you've made a change. This will motivate me to add those update checkpoints in.
